"""empty message

Revision ID: 922cf2361004
Revises: 53f12eedbe5f
Create Date: 2023-05-09 09:59:52.914325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922cf2361004'
down_revision = '53f12eedbe5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('healer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('healer')
    # ### end Alembic commands ###
